version: "3"
services:
  app:
    build: .
    command: python -m flask run --host 0.0.0.0 --port 5000
    environment:
      - FLASK_APP=serve.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  worker:
    build: .
    command: python -m flask rq worker --worker-ttl 420
    environment:
      - FLASK_APP=serve.py
    volumes:
      - .:/code
  redis:
    image: "redis:alpine"
